# Generated by Django 6.0.3 on 2026-03-08 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Annual Membership', max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='membership.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
