# Generated by Django 6.0.3 on 2026-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippurchase',
            name='price_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
