# Generated by Django 6.0.3 on 2026-03-07 17:57

import django.db.models.deletion
import rides.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_riders', models.PositiveIntegerField()),
                ('discipline', models.CharField(choices=[('road', 'Road'), ('gravel', 'Gravel'), ('mtb', 'MTB')], max_length=20)),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=rides.models.get_deleted_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
