# Generated by Django 6.0.3 on 2026-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
