# Generated by Django 6.0.3 on 2026-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
