# Generated by Django 6.0.3 on 2026-03-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_alter_notification_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ride_created', 'Ride created'), ('ride_joined', 'Ride joined'), ('ride_left', 'Ride left'), ('ride_comment', 'Ride comment')], max_length=20),
        ),
    ]
